# Generated by Django 3.1.4 on 2020-12-17 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nid_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='nid_pic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
