# Generated by Django 3.1.4 on 2020-12-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_rent', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
