# Generated by Django 3.1.4 on 2020-12-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_rent', '0004_remove_rent_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='price',
            field=models.FloatField(default=1500),
        ),
    ]
